### PR TITLE
Added dumper option to prevent splitting lines

### PR DESCRIPTION
**Pull request by vjkoskela**

### CODE REVIEW

**Comment by asomov** [comment]
Cool. Thank you. The only problem is that I cannot use hg-git to pull the commit. I am afraid I have to do it manually.

**Comment by vjkoskela** [comment]
I'm not sure that I see problem. The change can be merged here in Github into your repository or you can clone my repository which has the change from here:

https://github.com/vjkoskela/snakeyaml

However, if neither is an option I can package the patch in a different way. Just let me know what works.

**Comment by maslovalex** [comment]
It is not a problem to merge here, but to get back these changes to official repository. Which is mercurial one and hosted on googlecode. This git repo has been created using hg-git... But there are some issues with it now...

**Comment by vjkoskela** [comment]
Got it. Would you prefer I forked the mercurial repo on googlecode and made
a pull request against that?

On Thu, Feb 5, 2015 at 11:39 AM, maslovalex <notifications@github.com>
wrote:

> It is not a problem to merge here, but to get back these changes to
> official repository. Which is mercurial one and hosted on googlecode. This
> git repo has been created using hg-git... But there are some issues with it
> now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asomov/snakeyaml/pull/2#issuecomment-73111924>.
>



-- 
*Ville Koskela*
Software Engineer

505 5th Ave S, Suite 310, Seattle, WA 98104
Desk: 206-357-3354
Mobile: 206-973-6877
Groupon
<http://www.google.com/url?q=http%3A%2F%2Fwww.groupon.com%2F&sa=D&sntz=1&usg=AFrqEzcC80FkwsjyolWTKAH1sZ9yU2t0xg>
 II Grouponworks
<http://www.google.com/url?q=http%3A%2F%2Fwww.grouponworks.com%2F&sa=D&sntz=1&usg=AFrqEzdLBm3Dql75wz1BTY0mA30ov3RnWg>

**Comment by asomov** [comment]
It would be perfect. Unfortunately, Google code does not support pull requests.
Just make your change and let us know (via an issue). We will pull it.
If it becomes too difficult just let us lnow and I will create a patch myself

**Comment by vjkoskela** [comment]
Here's the change on my clone of the Google Code repository:

https://code.google.com/r/vkoskela-spltlines/source/detail?r=ca9cff4776ef7df3000a1b23c3057bc1544871b3

I've also attached a patch file in case you can't pull the change from
Google.

Cheers,
Ville

On Fri, Feb 6, 2015 at 7:38 AM, Andrey Somov <notifications@github.com>
wrote:

> It would be perfect. Unfortunately, Google code does not support pull
> requests.
> Just make your change and let us know (via an issue). We will pull it.
> If it becomes too difficult just let us lnow and I will create a patch
> myself
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asomov/snakeyaml/pull/2#issuecomment-73255351>.
>



-- 
*Ville Koskela*
Software Engineer

505 5th Ave S, Suite 310, Seattle, WA 98104
Desk: 206-357-3354
Mobile: 206-973-6877
Groupon
<http://www.google.com/url?q=http%3A%2F%2Fwww.groupon.com%2F&sa=D&sntz=1&usg=AFrqEzcC80FkwsjyolWTKAH1sZ9yU2t0xg>
 II Grouponworks
<http://www.google.com/url?q=http%3A%2F%2Fwww.grouponworks.com%2F&sa=D&sntz=1&usg=AFrqEzdLBm3Dql75wz1BTY0mA30ov3RnWg>

**Comment by asomov** [comment]
Thank you !
https://code.google.com/p/snakeyaml/wiki/changes

Cheers,
Andrey

**Comment by vjkoskela** [comment]
Terrific. Do you know whether there will be a February release this year?

**Comment by asomov** [comment]
Yes, it should be.

**Comment by asomov** [comment]
Hi Ville, unfortunately the test suite for this feature is incomplete.
Please check the issue: https://code.google.com/p/snakeyaml/issues/detail?id=206

**Comment by asomov** [comment]
Hi Ville, if you send the test suite this week it will be released with your fix. We are only waiting for to release 1.15

**Pull request closed without merging**
